### ISSUE TITLE
Running pyspa with Exiobase 

### ISSUE THREAD

**Issue by marpellan** [hybridlca/pyspa#4]
Dear pyspa developers, 

Thanks a lot for the module ! I am trying to run pyspa with Exiobase (e.g. a 9800 square matrix across 49 regions)

It has been running for several days, without any results for now. My computer has an  i5 processor with 16GB RAM, I wonder if it is necessary to run it on a server ? 

Thanks a lot for your feedback, 

Best regards

**Comment by andrestephan1** [comment]
Dear Marpellan

Thanks for reaching out. I'm glad you're finding pyspa useful.

Unfortunately, pyspa is not yet coded for multiprocessing. As such, it will run on one processor of your 16.

However, the process should not take this long. How many satellites are you using and what thresholds are you using? I would strongly recommend using the new feature in pyspa 2.4 'thresholds_as_percentages' and starting with a 5% threshold to really get a coarse idea, then gradually reducing your threshold. If you choose a very small threshold, you'll be combing through billions of transactions. For Exiobase, the total number of potential pathways at stage 7 is 9800^7 = 8.68 E27 (so 8.68 octillion transactions...)

Please let me know how you go.

**Comment by marpellan** [comment]
Dear andrestephan1, 

Thanks a lot for your quick feedback. 

I wasn't awared of the 'thresholds_as_percentages' features as I was running pyspa with an older version (1.4). 
I only used GHG emissions as satellites, but I used a 0.00001 thresholds with 8 stages, that would explain the very slow process. 

I have updated pyspa, indeed the percentage feature looks very useful! Now, it seems it is reading the A matrix, the thresholds and infosheet, but I get a KeyError: 'TR_GHGe_(kgCO2e)'. Any idea why it occurs? I haven't changed the infosheet file, and I cannot trace back the error. 

Thanks again for your help, 

Best regards

**Comment by marpellan** [comment]
Dear andrestephan1, 

Thanks a lot for your answer. Indeed, I was not using the latest version of pyspa and was not aware of the 'thresholds_as_percentages' feature. With a 1% threshold it is very fast. 

Thanks again for your help, 

Best regards

**Comment by andrestephan1** [comment]
Dear @marpellan , thanks for the update. Glad things seem to be working smoothly.
Don't hesitate to reach out if you encounter any issues.

Best wishes,
André
